nf_core_version: 3.1.0
repository_type: pipeline
template:
  author: James A. Fellows Yates, Sofia Stamouli, Moritz E. Beber, Lili Andersson-Li,
    and the nf-core/taxprofiler team
  description: Taxonomic classification and profiling of shotgun short- and long-read
    metagenomic data
  force: false
  is_nfcore: true
  name: taxprofiler
  org: nf-core
  outdir: .
  version: 1.3.0dev
